### ISSUE TITLE
Docker Container Backtesting is missing pandas_ta

### ISSUE THREAD

**Issue by loewensteinph** [iterativv/NostalgiaForInfinity#18]
Recent change broke Docker setup

_import talib.abstract as ta_ 

Change Docker Compose file - Replace Image with custom docker file

```yaml ---
version: '3'
services:
  backtesting:
    image: freqtradeorg/freqtrade:develop
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityNext.py:/freqtrade/NostalgiaForInfinityNext.py"
    command: >
      backtesting
      --strategy-list NostalgiaForInfinityNext
      --timerange ${TIMERANGE:-20210601-20210701}
      --config user_data/pairlists.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data --timerange 20201201-20210701 --timeframe 5m 1h --config user_data/pairlists.json
```
Change to
```yaml ---
version: '3'
services:
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityNext.py:/freqtrade/NostalgiaForInfinityNext.py"
    command: >
      backtesting
      --strategy-list NostalgiaForInfinityNext
      --timerange ${TIMERANGE:-20210601-20210701}
      --config user_data/pairlists.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data --timerange 20201201-20210701 --timeframe 5m 1h --config user_data/pairlists.json
```

Content of Dockerfile.custom in subfolder "docker"

```yaml
FROM freqtradeorg/freqtrade:develop
# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
USER root

# The below dependency - pyti - serves as an example. Please use whatever you need!
RUN pip install pandas_ta
RUN pip install --user pyti

USER ftuser
```
