### ISSUE TITLE
ERROR - Impossible to load Strategy 'NostalgiaForInfinityNext'. This class does not exist or contains Python code errors.

### ISSUE THREAD

**Issue by taygun08** [iterativv/NostalgiaForInfinity#435]
### PROBLEM
I wrote a docker yml to simulate 2 strategies together, but the *NEXT strategy gives an python error. 
### my docker-compose yml
note: In the freqtrade2 section, it was using .env, not .env2, so I used static input.
```
services:
  freqtrade1:
    # image: freqtradeorg/freqtrade:stable
    image: freqtrade_with_numba
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: ${FREQTRADE__BOT_NAME:-Example_Test_Account}_${FREQTRADE__EXCHANGE__NAME:-binance}_${FREQTRADE__TRADING_MODE:-futures}-${FREQTRADE__STRATEGY:-NostalgiaForInfinityX5}
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./user_data/logs:/freqtrade/user_data/logs"
      - "./configs:/freqtrade/configs"
      - "./${FREQTRADE__STRATEGY:-NostalgiaForInfinityX5}.py:/freqtrade/${FREQTRADE__STRATEGY:-NostalgiaForInfinityX5}.py"
    ports:
      - "${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}:${FREQTRADE__API_SERVER__LISTEN_PORT:-8080}"
    # Default command used when running `docker compose up`
    env_file:
      - .env
    command: >
      trade
      --db-url sqlite:////freqtrade/user_data/${FREQTRADE__BOT_NAME:-Example_Test_Account}_${FREQTRADE__EXCHANGE__NAME:-binance}_${FREQTRADE__TRADING_MODE:-futures}-tradesv3_freqtrade1.sqlite
      --log-file user_data/logs/${FREQTRADE__BOT_NAME:-Example_Test_Account}-${FREQTRADE__EXCHANGE__NAME:-binance}-${FREQTRADE__STRATEGY:-NostalgiaForInfinityX5}-${FREQTRADE__TRADING_MODE:-futures}_freqtade1.log
      --config /freqtrade/user_data/config_freqtrade1.json
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command:
      [
        "/bin/sh",
        "-c",
        "while true; do sleep 86400; docker restart ${FREQTRADE__BOT_NAME:-Example_Test_Account}_${FREQTRADE__EXCHANGE__NAME:-binance}_${FREQTRADE__TRADING_MODE:-futures}-${FREQTRADE__STRATEGY:-NostalgiaForInfinityX5}; done",
      ]
    restart: unless-stopped

  freqtrade2:
    # image: freqtradeorg/freqtrade:stable
    image: freqtrade_with_numba
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
#    container_name: freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext
    container_name: freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./user_data/data:/freqtrade/user_data/data"
      - "./user_data/logs:/freqtrade/user_data/logs"
      - "./configs:/freqtrade/configs"
      - "./NostalgiaForInfinityNext.py:/freqtrade/NostalgiaForInfinityNext.py"
    ports:
      - "8081:8081"
    # Default command used when running `docker compose up`
    env_file:
      - .env2
    command: >
      trade
      --db-url sqlite:////freqtrade/user_data/freqtrade2_Test_Account_binance_futures-tradesv3_freqtrade2.sqlite
      --log-file user_data/logs/freqtrade2_Test_Account-binance-NostalgiaForInfinityNext-futures_freqtrade2.log
      --config /freqtrade/user_data/config_freqtrade2.json
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command:
      [
        "/bin/sh",
        "-c",
        "while true; do sleep 86400; docker restart freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext; done",
      ]
    restart: unless-stopped

```
### tests/requirements.txt file
```
# freqtrade==2024.5
# freqtrade @ git+https://github.com/freqtrade/freqtrade@releases/tag/2024.5
freqtrade
pandas-ta
pytest
pytest-mock
pytest-subtests
pytest-xdist
ast_comments
docxtpl
pytest-md
pytest-pretty
numba

```
### ERROR:
```
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,365 - freqtrade.configuration.load_config - INFO - Using config: /freqtrade/user_data/config_freqtrade2.json ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,365 - freqtrade.configuration.load_config - INFO - Using config: ../configs/trading_mode-futures.json ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,366 - freqtrade.configuration.load_config - INFO - Using config: ../configs/pairlist-volume-binance-usdt.json ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,366 - freqtrade.configuration.load_config - INFO - Using config: ../configs/blacklist-binance.json ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,366 - freqtrade.configuration.load_config - INFO - Using config: ../configs/exampleconfig.json ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,367 - freqtrade.configuration.load_config - INFO - Using config: ../configs/exampleconfig_secret.json ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,367 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__API_SERVER__ENABLED'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,367 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__API_SERVER__JWT_SECRET_KEY'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__API_SERVER__LISTEN_PORT'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__API_SERVER__PASSWORD'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__API_SERVER__USERNAME'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__API_SERVER__WS_TOKEN'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__BOT_NAME'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__DRY_RUN'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__EXCHANGE__KEY'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__EXCHANGE__NAME'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,368 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__EXCHANGE__SECRET'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,369 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__MAX_OPEN_TRADES'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,369 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__STRATEGY'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,369 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__TELEGRAM__CHAT_ID'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,369 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__TELEGRAM__ENABLED'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,369 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__TELEGRAM__TOKEN'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,369 - freqtrade.configuration.environment_vars - INFO - Loading variable 'FREQTRADE__TRADING_MODE'
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,370 - freqtrade.loggers - INFO - Verbosity set to 0
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,371 - freqtrade.configuration.configuration - INFO - Runmode set to dry_run.
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,371 - freqtrade.configuration.configuration - INFO - Parameter --db-url detected ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,371 - freqtrade.configuration.configuration - WARNING - `force_entry_enable` RPC message enabled.
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,371 - freqtrade.configuration.configuration - INFO - Dry run is enabled
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,371 - freqtrade.configuration.configuration - INFO - Using DB: "sqlite:////freqtrade/user_data/freqtrade2_Test_Account_binance_futures-tradesv3_freqtrade2.sqlite"
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,372 - freqtrade.configuration.configuration - INFO - Using max_open_trades: 10 ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,402 - freqtrade.configuration.configuration - INFO - Using user-data directory: /freqtrade/user_data ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,402 - freqtrade.configuration.configuration - INFO - Using data directory: /freqtrade/user_data/data/binance ...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,404 - freqtrade.exchange.check_exchange - INFO - Checking exchange...
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,425 - freqtrade.exchange.check_exchange - INFO - Exchange "binance" is officially supported by the Freqtrade development team.
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,425 - freqtrade.configuration.configuration - INFO - Using pairlist from configuration.
freqtrade2_Test_Account_binance_futures-NostalgiaForInfinityNext | 2024-10-28 00:44:02,426 - freqtrade - ERROR - Impossible to load Strategy 'NostalgiaForInfinityNext'. This class does not exist or contains Python code errors.

```
